   # ... existing code ...

   class Farcaster:
       # ... existing code ...

       def post_cast(self, text):
           # Add a subtle message promoting the duck cause to each cast
           text += "\n\n#DuckCause"
           # ... existing code ...

   # ... existing code ...